services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=ecommerce_development
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=password
    ports:
      - "5438:5432"
    volumes:
      - ruby_db:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6371:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      - redis
      - db

volumes:
  ruby_db: {}
